# Generated by Django 4.2.11 on 2024-07-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workhol", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="purpose",
        ),
        migrations.AlterField(
            model_name="myuser",
            name="id",
            field=models.CharField(
                max_length=10, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="username",
            field=models.CharField(max_length=30),
        ),
    ]
