# Generated by Django 4.2.11 on 2024-07-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workhol", "0002_remove_myuser_purpose_alter_myuser_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="gender",
            field=models.CharField(choices=[("M", "남자"), ("F", "여자")], max_length=1),
        ),
    ]
