# Generated by Django 5.0.6 on 2024-07-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workhol', '0005_category_continent_site_country_sitecategory_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='continent_name',
            field=models.CharField(choices=[('AS', '아시아'), ('EU', '유럽'), ('NA', '북아메리카'), ('SA', '남아메리카'), ('AF', '아프리카'), ('OC', '오세아니아'), ('ME', '중동')], max_length=10, unique=True),
        ),
    ]
