# Generated by Django 5.0.6 on 2024-07-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workhol', '0006_alter_continent_continent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
